spring:
  profiles:
    active: local
  application:
    name: Network-Office

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

oauth:
  kakao:
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    access-token-request-url: ${OAUTH_KAKAO_ACCESS_TOKEN_REQUEST_URI}
    user-information-request-url: ${OAUTH_KAKAO_USER_INFORMATION_REQUEST_URI}
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}

logging.level:
  org.hibernate.SQL: debug