# Default, Local
spring:
  application:
    name: Network-Office

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  session:
    redis:
      namespace: ${REDIS_SESSION_NAMESPACE}

server:
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

oauth:
  kakao:
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    access-token-request-url: ${OAUTH_KAKAO_ACCESS_TOKEN_REQUEST_URI}
    user-information-request-url: ${OAUTH_KAKAO_USER_INFORMATION_REQUEST_URI}
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}

email:
  imap:
    server: ${EMAIL_IMAP_SERVER}
    port: ${EMAIL_IMAP_PORT}
  account: ${EMAIL_ACCOUNT}
  password: ${EMAIL_PASSWORD}

swagger:
  server:
    dev: ${DEV_SERVER_URL}

logging.level:
  org.hibernate.SQL: debug

---
# Dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false

server:
  servlet:
    session:
      cookie:
        secure: true