# Common
spring:
  application:
    name: Network-Office

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

oauth:
  kakao:
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    access-token-request-url: ${OAUTH_KAKAO_ACCESS_TOKEN_REQUEST_URI}
    user-information-request-url: ${OAUTH_KAKAO_USER_INFORMATION_REQUEST_URI}
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}

swagger:
  server:
    dev: ${DEV_SERVER_URL}

---
# Local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create

---
# Dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false